services:
  app:
    container_name: blog
    build: ./app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql
    container_name: blog-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=blog
      - MYSQL_PASSWORD=blog
      - MYSQL_DATABASE=sample


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - "8081:80"
